spring:
  application:
    name: auth-service
  # Database config
  datasource:
#    url: jdbc:mysql://mysql8:3306/red_social_local?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost:3306}/${MYSQL_DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  # Configuration of Spring Email
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    protocol: smtp
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

google:
  clientId: ${GOOGLE_CLIENT_ID:clientid}
  clientSecret: ${GOOGLE_SECRET_ID:secretid}
  commomPassword: ${GOOGLE_COMMON_PASSWORD:j137921}

server:
  port: ${PORT:8091}

app:
  security:
    failsAttemps: 3
    jwtSecret: ${JWT_SECRET}
    jwtExpirationTimeMs: 3600000
    jwtRefreshExpirationMs: 86400000


