spring:
  application:
    name: auth-service
  # Database config
  datasource:
    url: jdbc:mysql://localhost:3306/tasks_local?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: rootpassword #root123-
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  # Configuration of Spring Email
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ingresoegresoapprosario@gmail.com
    password: rhoictioskmdfpzo
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

server:
  port: 8091

app:
  security:
    failsAttemps: 3
    jwtSecret: kase235mdsgr2
    jwtExpirationTimeMs: 3600000
    jwtRefreshExpirationMs: 86400000


