spring:
  application:
    name: user-service
    security:
      user:
        password: 12121
  # Database config
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST}/${MYSQL_DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  # File size config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT}

auth:
  service:
    uri: ${AUTH_SERVICE_URI}

paths:
  common-image-directory:
#    location:
    location: ${FILE_DIRECTORY}

cloudinary:
  active: true
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
  profile_photo_filters: resize, improve_photo, resize_based_face_detection
  host: ${CLOUDINARY_HOST}
  delete_uri: ${CLOUDINARY_DELETE_URI}