spring:
  application:
    name: user-service
    security:
      user:
        password: 12121
  # Database config
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_local?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root123-
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

server:
  port: 8092

auth:
  service:
    uri: http://localhost:8091


