server:
  port: 8090

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/security/**

#        - id: test-architecture
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/test/**
#          filters:
#            - StripPrefix=2
        - id: user-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/users/**
